name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

template: |
  ## What’s Changed
  $CHANGES
  ## Steps to rolback
  1. Rollback to [$PREVIOUS_TAG](https://github.com/javierpedreira/actions_playground/releases/$PREVIOUS_TAG) 
  **Full Changelog**: https://github.com/javierpedreira/actions_playground/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
  ## QA report
categories:
  - title: '💥 High Risk changes'
    label: 'major'
  - title: '⚠️ Medium Risk changes'
    label: 'medium'
  - title: '✨ New thingies'
    label: 'feature'
  - title: '🐛 Bug fixes'
    label: 'bug'    
version-resolver:
  major:
    labels:
      - 'major'
      - 'RED_ALERT'
  minor:
    labels:
      - 'medium'
      - 'feature'
  default: minor
  