name: pepe

on:
  workflow_call:
    inputs:
      username:
        required: false
        type: string

jobs:
  test-auto-builds:
    runs-on: ubuntu-latest
    env:
      ENV: "staging"
      REPO: "insights-explorer"
      BRANCH: "staging-ie-auto-deploy"
  steps:
    - name: DO THE THING
      run: /
        echo "HELLO WORLD"
