name: pepe

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      repo:
        required: true
        type: string
      condition:
        required: false
        type: boolean
jobs:
  test-auto-builds:
    runs-on: ubuntu-latest
    env:
      ENV: "staging"
      REPO: "insights-explorer"
      BRANCH: "staging-ie-auto-deploy"
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script ${{ inputs.service }}
        run: echo Releasing libs! ${{ inputs.service }} ${{ inputs.repo }}
      - name: Runs if true
        run: echo Releasing libs IF I CAN! ${{ inputs.service }} ${{ inputs.repo }}
        if: ${{ inputs.condition }}
